services:
  pdf-generator:
    build: .
    container_name: pdf-generator
    ports:
      - "15148:15148"
    restart: unless-stopped

networks:
  default:
    name: app-sso-network
    external: true