version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: always
    container_name: android-static-redis

  android-static-backend:
    build: .
    restart: always
    container_name: android-static-backend
    ports:
      - "8010:8010"

  queue-wrapper:
    build: ./queue_wrapper
    restart: always
    container_name: android-static-wrapper
    ports:
      - "5001:5001"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - android-static-backend

  celery-worker:
    build: ./queue_wrapper
    restart: always
    command: celery -A tasks worker --loglevel=info --concurrency=1
    environment:
      - ANDROGUARD_BASE=http://android-static-backend:8010
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - android-static-backend

networks:
  default:
    name: app-sso-network
    external: true
